import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { container, navbar, main, title } = styles;
  return (
    <div className={container}>
      <style jsx global>
        {`
          .title-bg {
            background-color: gray;
            color: white;
            padding: 10px 20px;
          }
        `}
      </style>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={navbar}>
        <ul>
          <Link href="/">
            <a>
              <li>Home</li>
            </a>
          </Link>
          <Link href="/blogs">
            <a>
              <li>Blogs</li>
            </a>
          </Link>
          <Link href="/about">
            <a>
              <li>About</li>
            </a>
          </Link>
          <Link href="/contact">
            <a>
              <li>Contact</li>
            </a>
          </Link>
        </ul>
      </nav>

      <main className={main}>
        <h1 className={`${title} title-bg`}>
          Welcome to{" "}
          <a href="https://www.linkedin.com/in/shahrear-ahamed/">Shahrear</a>
          Blog
        </h1>

        <div>
          <h2>My Blogs</h2>
          <div>
            <h3>I just start Next js courses for learn Next.js</h3>
            <p>
              Next js is a most popular javascript react js framework. which is
              provide us lot of features for making website fast and unique.
            </p>
          </div>
          <div>
            <h3>I just start Next js courses for learn Next.js</h3>
            <p>
              Next js is a most popular javascript react js framework. which is
              provide us lot of features for making website fast and unique.
            </p>
          </div>
          <div>
            <h3>I just start Next js courses for learn Next.js</h3>
            <p>
              Next js is a most popular javascript react js framework. which is
              provide us lot of features for making website fast and unique.
            </p>
          </div>
          <div>
            <h3>I just start Next js courses for learn Next.js</h3>
            <p>
              Next js is a most popular javascript react js framework. which is
              provide us lot of features for making website fast and unique.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
